[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true # Ensure that we always redirect

  [[headers]]
    for = "/service-worker.js"
      [headers.values]
        cache-control = '''
          max-age=0,
          no-cache,
          no-store,
          must-revalidate'''