name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
  
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: patzick/merger@master
    - name: Run test action
      run: echo Hello, world!
